### ISSUE TITLE
Remove keys for undefined values from the query string when using getQuery

### ISSUE THREAD

**Issue by firedev** [springboardretail/api-operations#2]
In `sr/lib/query_string{ generate }` we have a check for `undefined` values and the key is not added to string.

When using `getQuery` it sends empty keys anyway and that breaks our API.

Given:

```
Api.getQuery('/', { key: undefined })
```

Expected:

```
/
```

Actual:

```
/?key=
```

**Comment by burabure** [comment]
@firedev fixed in 1.2.1 =)
