### ISSUE TITLE
Add an option to send body on delete request

### ISSUE THREAD

**Issue by fyodoriv** [springboardretail/api-operations#3]
Hey, I've noticed that the current implementation does not allow sending a body on delete request.
This is needed in SR logic (while deleting a ticket line for instance) and also I did some research and apparently a body is permitted inside a DELETE request (https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19 6.7 and https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request). So I don't think there is a reason not to support it here.

**Comment by burabure** [comment]
this is a complicated one, historically a body on a delete request has been non-standard implementation for servers and avoided by libraries. The most up to date spec states 

```
A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.
```

https://tools.ietf.org/html/rfc7231#section-4.3.5

Which basically translates to "you can tecnically use a body on a delete request, but it's not standard"

I think the best way to do it it's just to pass the body in the fetchOptions param:

``` js
const fetchOptions = {
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(someBody),
}

// standalone method
delete_('http://myUrl/', fetchOptions)

// apiSource method
myAPISource.delete('someEndpoint', fetchOptions)
```

but that's a little bit too low level; I guess I can expose the sendJson method (https://github.com/springboardretail/api-operations/blob/master/src/apiOperations.js#L23-L32) for non-standard or non-supported cases and extension.

**Comment by burabure** [comment]
sendJson is out on v1.3.0

``` js
sendJson('http://myCoolApi.com/endpoint', { myData: 'omgBbqWtfKawaii' }, { method: 'delete' })
```
