### ISSUE TITLE
Add an option to operationOptions for custom JSON parse 

### ISSUE THREAD

**Issue by fyodoriv** [springboardretail/api-operations#5]
Hey, I have another use case.
I need to change returned JSON before converting it into an object to remove the '?' sign from all keys. It's more optimal to do it with regex while it's a JSON string than removing/adding keys when JSON is already parsed.

So the idea to do that would be to add an option `customParser` or something to an `operationOptions` object, which will trigger here https://github.com/springboardretail/api-operations/blob/master/src/apiOperations.js#L17 instead of default `parseResponse`.

**Comment by burabure** [comment]
You can do this using the `dontParse` setting

``` js
get('https://test/dontParse', {}, { dontParse: true })
  .then(response =>  response.text())  // https://developer.mozilla.org/es/docs/Web/API/Response
  .then(text => myStringToJsonParser(text)  )
```

But it's probably going to be easier just to do:

``` js
get('https://test/endpoint')
  .then(json => Object.keys(json).reduce((obj, key) => (
    {...obj, [key.replace(/\?/g, '')]: json[key]) }
))
```

**Comment by fyodoriv** [comment]
Yeah I forgot about `dontParse`, thanks. The second option is not easier since I need to recursively rename keys.
