### ISSUE TITLE
Array query params are being parsed incorrectly

### ISSUE THREAD

**Issue by dwayne** [springboardretail/api-operations#6]
```
> qs = require('querystring')
> qs.stringify({ _include: ['a', 'b'] })
'_include=a&_include=b'
```
However, our API expects it to be `'_include[]=a&_include[]=b'`.

See [here](https://github.com/springboardretail/api-operations/blob/master/src/apiOperations.js#L47).

In the meantime, I'm working around the issue by using `_include[]` directly.

**Comment by burabure** [comment]
`querystring` is not part of this lib. You can pass an object to the `getQuery` method directly and it will handle "stringyfication" internally https://github.com/springboardretail/api-operations#getquery-url-query-fetchoptions-operationoptions

**Comment by dwayne** [comment]
@burabure Oh, I was just indicating how `querystring` works when the parameter is an array. Since it's used [here](https://github.com/springboardretail/api-operations/blob/master/src/apiOperations.js#L47) to "stringify" the parameters the final URL is incorrect.

`getQuery('http://myCoolApi.com/endpoint', { _include: ['a', 'b'] })` results in the URL, `http://myCoolApi.com/endpoint?_include=a&_include=b`.

But, the correct URL is `http://myCoolApi.com/endpoint?_include[]=a&_include[]=b`.

I worked around the issue by essentially doing, `getQuery('http://myCoolApi.com/endpoint', { '_include[]': ['a', 'b'] })`. But I think this library should handle that.

**Comment by burabure** [comment]
I see, yeah I remember now. The thing is that that way of encoding arrays is particular to springboard's api and this lib is more of a general purpose dep. I think we should implement that as a helper layer on the sr codebase.
